---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: production-ip-pool
      protocol: layer2
      addresses:
      - 10.61.1.30-10.61.1.50
      avoid-buggy-ips: true
      auto-assign: true

